"""Schema definitions for expected synthetic datasets."""

from __future__ import annotations

DATASET_SCHEMAS: dict[str, list[str]] = {
    "01_padron_votantes.csv": [
        "voter_id",
        "documento_hash",
        "fecha_nacimiento",
        "edad",
        "fecha_defuncion",
        "estado_documento",
        "condicion_legal",
        "habilitado_legalmente",
        "estado_padron",
        "municipio",
        "zona_id",
        "circunscripcion_autorizada",
        "mesa_asignada",
    ],
    "02_asignacion_mesas.csv": [
        "voter_id",
        "mesa_asignada",
        "puesto_asignado",
        "zona_asignada",
        "municipio_asignado",
        "circunscripcion_autorizada",
        "tipo_boleta_autorizada",
        "puede_votar_en_otro_puesto",
        "justificacion_excepcion",
    ],
    "03_registro_sufragio.csv": [
        "suffrage_id",
        "voter_id",
        "fecha_eleccion",
        "voto_registrado",
        "mesa_voto",
        "puesto_voto",
        "zona_voto",
        "municipio_voto",
        "circunscripcion_voto",
        "hora_checkin",
        "metodo_checkin",
        "operador_checkin",
    ],
    "04_clasificacion_votos_manual.csv": [
        "ballot_id",
        "mesa_id",
        "voter_id",
        "marca_simulada",
        "clasificacion_objetiva",
        "clasificacion_jurado",
        "clasificacion_auditoria",
        "usuario_clasificador",
    ],
    "05_resultados_mesa.csv": [
        "mesa_id",
        "municipio",
        "zona_id",
        "circunscripcion",
        "electores_habilitados",
        "sufragantes_registrados",
        "votos_candidato_A",
        "votos_candidato_B",
        "votos_candidato_C",
        "votos_blancos",
        "votos_nulos",
        "votos_invalidos",
        "total_calculado",
        "total_reportado",
        "participacion_pct",
        "ganador",
        "concentracion_ganador_pct",
        "margen_victoria_pct",
    ],
    "06_logs_eventos.csv": [
        "evento_id",
        "timestamp",
        "usuario_id",
        "rol_usuario",
        "accion",
        "recurso",
        "mesa_id",
        "zona_id",
        "resultado_accion",
        "ip_origen",
        "requiere_aprobacion",
        "aprobado_por",
        "hash_antes",
        "hash_despues",
    ],
    "07_integridad_archivos.csv": [
        "archivo_id",
        "tipo_archivo",
        "mesa_id",
        "version",
        "hash_original",
        "hash_actual",
        "timestamp_firma",
        "timestamp_publicacion",
        "usuario_publicador",
        "estado_integridad",
        "reporte_firmado_total",
        "reporte_publicado_total",
    ],
    "08_alertas_esperadas.csv": [
        "alerta_id",
        "codigo_alerta",
        "entidad_tipo",
        "entidad_id",
        "dataset_origen",
        "severidad",
        "descripcion",
    ],
    "usuarios_sistema.csv": [
        "usuario_id",
        "nombre_usuario",
        "rol",
        "estado_usuario",
        "zona_asignada",
        "mesa_asignada",
        "puede_modificar_padron",
        "puede_registrar_sufragio",
        "puede_clasificar_votos",
        "puede_modificar_resultados",
        "puede_aprobar_cambios",
        "puede_ver_logs",
        "requiere_mfa",
    ],
}

ALLOWED_VALUES: dict[str, set[str]] = {
    "estado_documento": {"vigente", "cancelado", "inconsistente"},
    "condicion_legal": {"normal", "inhabilitado", "privado_libertad", "fallecido"},
    "estado_padron": {"activo", "inactivo"},
    "tipo_boleta_autorizada": {"nacional", "municipal", "especial"},
    "metodo_checkin": {"manual", "electronico"},
    "marca_simulada": {
        "candidato_A",
        "candidato_B",
        "candidato_C",
        "blanco",
        "marca_ambigua",
        "multiple_marca",
        "sin_marca",
    },
    "clasificacion_objetiva": {"valido", "blanco", "nulo", "invalido"},
    "clasificacion_jurado": {"valido", "blanco", "nulo", "invalido"},
    "clasificacion_auditoria": {"valido", "blanco", "nulo", "invalido"},
    "rol_usuario": {
        "ADMIN_ELECTORAL",
        "OPERADOR_PADRON",
        "JURADO_MESA",
        "CLASIFICADOR_MANUAL",
        "SUPERVISOR_ESCRUTINIO",
        "OPERADOR_TECNICO",
        "ANALISTA_SEGURIDAD",
        "AUDITOR",
        "SERVICIO_SISTEMA",
    },
    "tipo_archivo": {"acta", "resultado_mesa", "snapshot_publicacion", "log_exportado"},
    "estado_integridad": {"integro", "alterado", "pendiente_revision"},
    "severidad": {"critica", "alta", "media"},
    "entidad_tipo": {"voter_id", "mesa_id", "ballot_id", "usuario_id", "archivo_id", "evento_id", "suffrage_id"},
    "estado_usuario": {"activo", "inactivo", "suspendido"},
}

NUMERIC_COLUMNS: dict[str, list[str]] = {
    "01_padron_votantes.csv": ["edad", "habilitado_legalmente"],
    "02_asignacion_mesas.csv": ["puede_votar_en_otro_puesto"],
    "03_registro_sufragio.csv": ["voto_registrado"],
    "05_resultados_mesa.csv": [
        "electores_habilitados",
        "sufragantes_registrados",
        "votos_candidato_A",
        "votos_candidato_B",
        "votos_candidato_C",
        "votos_blancos",
        "votos_nulos",
        "votos_invalidos",
        "total_calculado",
        "total_reportado",
        "participacion_pct",
        "concentracion_ganador_pct",
        "margen_victoria_pct",
    ],
    "06_logs_eventos.csv": ["requiere_aprobacion"],
    "07_integridad_archivos.csv": ["version", "reporte_firmado_total", "reporte_publicado_total"],
    "usuarios_sistema.csv": [
        "puede_modificar_padron",
        "puede_registrar_sufragio",
        "puede_clasificar_votos",
        "puede_modificar_resultados",
        "puede_aprobar_cambios",
        "puede_ver_logs",
        "requiere_mfa",
    ],
}

ID_COLUMNS: dict[str, str] = {
    "01_padron_votantes.csv": "voter_id",
    "02_asignacion_mesas.csv": "voter_id",
    "03_registro_sufragio.csv": "suffrage_id",
    "04_clasificacion_votos_manual.csv": "ballot_id",
    "05_resultados_mesa.csv": "mesa_id",
    "06_logs_eventos.csv": "evento_id",
    "07_integridad_archivos.csv": "archivo_id",
    "08_alertas_esperadas.csv": "alerta_id",
    "usuarios_sistema.csv": "usuario_id",
}

DATASET_ORDER: list[str] = [
    "01_padron_votantes.csv",
    "02_asignacion_mesas.csv",
    "03_registro_sufragio.csv",
    "04_clasificacion_votos_manual.csv",
    "05_resultados_mesa.csv",
    "06_logs_eventos.csv",
    "07_integridad_archivos.csv",
    "08_alertas_esperadas.csv",
    "usuarios_sistema.csv",
]
